### ISSUE TITLE
Activity leak on interstitial and rewarded

### ISSUE THREAD

**Issue by gerzalez-x3m** [ChartBoost/chartboost-mediation-android-adapter-google-bidding#55]
**Summary of Issue**

An Android activity leak is detected after displaying a rewarded or interstitial ad.

**Reproduction Steps**

    1. fullscreenAd.showFullscreenAdFromJava(activity,listener) 
    2. Destroy Activity
    3. Run LeakCanary or Android Studio Memory Profiler
    4. Dump memory
    5. Detect that the Activity that show the ad is leaking thought com.chartboost.mediation.googlebiddingadapter.GoogleBiddingAdapter$showInterstitialAd$1 instance

**Expected Behavior**

No leaks after destroying the Android Activity

---

**Chartboost Mediation Integration Details**

 - Chartboost Mediation SDK version: 4.7.1
 - Partner Network SDK version: 22.3.0
 - Partner Adapter version: 4.22.3.0.4

**Android Environment Details**

 - Android Studio version:  2022.3.1 Patch 2
 - Gradle version: 7.6.2
 - Android Gradle Plugin version: 7.6.2
 - Java/Kotlin version: Kotlin 1.8.22
 - Unity Editor version (if this is a Unity build): not apply

**Device Details**

 - Device: Xiaomi Model M2004J19G
 - OS: 12

---

**Additional Context**

[Leak Canary stacktrace analysis](https://github.com/ChartBoost/chartboost-mediation-android-adapter-google-bidding/files/13864568/helium_google_bidding_leak_canary_stacktrace.txt)

<img width="1504" alt="Android Studio Memory Profiler screenshot" src="https://github.com/ChartBoost/chartboost-mediation-android-adapter-google-bidding/assets/110118032/80df0b7d-5446-44e4-9b92-60ca03ff7663">

**Comment by chauduyphanvu** [comment]
https://github.com/ChartBoost/chartboost-mediation-android-adapter-google-bidding/pull/59

**Comment by chauduyphanvu** [comment]
This has been fixed in https://github.com/ChartBoost/chartboost-mediation-android-adapter-google-bidding/commit/a3b10cc37d8d4b2f37c9afcc1fd0178f68b44ca7. Thanks for the cooperation on this one!

A release should be going out any minutes now.

**Comment by gerzalez-x3m** [comment]
Hi Chauduyphanvu!

Great to hear that the issue has been resolved! We'll be sure to test it
and let you know if everything checks out. Thanks for the update!

Best,
German Gonzalez
